Feature/ogn2 169
alkemyTech/React-SXXI-T2 pull request #101
Opened 2022-12-13 08:39 UTC by YamilChaju

Formulario de busqueda de usuarios finalizado

2022-12-14 22:17 UTC, milandre requested changes

2022-12-14 22:17 UTC, milandre commented on src/Components/Users/UsersSearch.jsx
> +    <input value={search} onChange={handleChange} type="text" placeholder="Buscar" className="users-search-bar" />
Estoy viendo la barra de búsqueda al medio pero en otros PR está hacia la izquierda, ¿Con cuál estilo se van a quedar? @YamilChaju

2022-12-14 22:17 UTC, milandre commented on src/Components/Users/UsersSearch.jsx
> +export const UsersSearch = ({ setUsers }) => {
Me gustó que sea un componente. Como sugerencia de mejora para próximos proyectos: Intentar hacer este componente lo más reutilizable posible asi las otras vistas que tienen que usar esta barra de búsqueda lo puedan usar y los cambios de estilos y funcionalidades solo se hagan en un solo componente

2022-12-15 07:31 UTC, YamilChaju commented on src/Components/Users/UsersSearch.jsx
> +export const UsersSearch = ({ setUsers }) => {
Lo voy a tener en cuenta, gracias!

2022-12-15 07:33 UTC, YamilChaju commented on src/Components/Users/UsersSearch.jsx
> +    <input value={search} onChange={handleChange} type="text" placeholder="Buscar" className="users-search-bar" />
@milandre Conversando con el equipo decidimos dejarlo en el medio, pronto vamos a estar cambiando los demas buscadores para que queden igual.

2022-12-16 01:16 UTC, merged