Feature/ogn2 53
alkemyTech/React-SXXI-T2 pull request #13
Opened 2022-11-02 15:25 UTC by JuanmeGarcia

Termine el componente slider. Toma todo el porcentaje del ancho y alto, por lo que se debe colocar dentro de una etiqueta contenedora para delimitarlo

2022-11-06 22:42 UTC, milandre requested changes

2022-11-06 22:42 UTC, milandre commented on src/App.js
> +import { Register } from './pages'
Esto debería ir también en la linea 15 si lo van a dejar en la carpeta Pages. Hay dos carpetas pages y Pages que tiene que decidir con cual se quedan

2022-11-06 22:42 UTC, milandre commented on src/pages/index.js
> +export * from './Register'
Sale error acá porque el componente Register no está acá si no en Pages

2022-11-06 22:42 UTC, milandre commented on src/pages/index.js
> +export * from './Home'
Sale error acá porque el componente Home no está acá si no en Pages

2022-11-06 22:42 UTC, milandre commented on src/App.js
> +          <Route path="/" element={<Home />} />
Falta import del componente `<Home />`

2022-11-06 22:42 UTC, milandre commented on src/Pages/Home.jsx
> +}
Falta el export default

2022-11-06 22:42 UTC, milandre commented on src/index.js
> -  <React.StrictMode>
¿Por qué sacar el strict mode?

2022-11-06 22:42 UTC, milandre commented on src/Components/Slider/Slider.jsx
> +            title={selectedImage.description}
Dejar el texto de la descripción sin los tags de HTML.

2022-11-06 22:42 UTC, milandre commented on src/Components/Slider/Slider.jsx
> +                    alt={selectedImage.description}
Dejar el texto de la descripción sin los tags de HTML.

2022-11-09 18:04 UTC, JuanmeGarcia commented on src/Pages/Home.jsx
> +}
tiene el export al lado del a function

2022-11-09 18:05 UTC, JuanmeGarcia commented on src/index.js
> -  <React.StrictMode>
Perdon, lo saque para debuggear algo y que no haya tanto ruido en la consola

2022-11-09 18:06 UTC, JuanmeGarcia commented on src/Components/Slider/Slider.jsx
> +                    alt={selectedImage.description}
Como? No entiendo esta parte

2022-11-10 11:54 UTC, milandre requested changes

2022-11-10 11:54 UTC, milandre commented on src/Components/Slider/Slider.jsx
> +    console.log(description);
Borrar console.log

2022-11-10 15:47 UTC, milandre commented
@JuanmeGarcia ahi te dejé el comentario del console.log que falta eliminar y apruebo el PR.

2022-11-10 15:48 UTC, milandre approved these changes

2022-11-11 19:33 UTC, JuanmeGarcia commented
Hago el merge ?

2022-11-11 21:07 UTC, milandre commented
@JuanmeGarcia ustedes se encargan del merge. Ten en cuenta los conflictos que puedan existir con archivos y asegúrense de que la rama de development quede sin errores.

2022-11-11 22:23 UTC, merged