Feature/ong2 25
alkemyTech/React-SXXI-T2 pull request #16
Opened 2022-11-02 18:58 UTC by CatrielNanthaveth

2022-11-04 21:15 UTC, YamilChaju approved these changes

2022-11-09 11:48 UTC, milandre requested changes

2022-11-09 11:48 UTC, milandre commented on src/Components/Auth/RegisterForm.jsx
>  export const RegisterForm = () => {
Los estilos del form hay que revisarlos. Se ve el formulario con los inputs muy a la izquierda
![image](https://user-images.githubusercontent.com/5572252/200822291-f40cdb73-599a-44fd-927d-76abef421011.png)

2022-11-09 18:08 UTC, CatrielNanthaveth commented
@milandre qué tal profe, ya he corregido las reviews. Si puede verificar nuevamente lo agradecería.

2022-11-10 16:15 UTC, milandre requested changes
@CatrielNanthaveth hay un detalle con la validación de la contraseña. Revisar el RegEx. 

Pruebo esta contraseña y me sale `Por favor ingrese una contraseña más fuerte` y no debería: pruebatest1!

2022-11-12 16:31 UTC, CatrielNanthaveth commented
@milandre si puede verificar si hay errores nuevamente lo agradecería.
También he de avisar que dejé los estilos del register en el formStyles.css porque el Login de Kevin dependía del css del register. Cuando se suba este componente y sus cambios, haremos que el login dependa nuevamente del register pero no del css sino del scss y borraremos el código css del formStyles que refieran al register.

2022-11-13 16:48 UTC, milandre approved these changes

2022-11-13 18:02 UTC, merged