Bugfix/ogn2 51
alkemyTech/React-SXXI-T2 pull request #18
Opened 2022-11-03 17:23 UTC by JuanmeGarcia

2022-11-03 20:38 UTC, milandre requested changes
@JuanmeGarcia estás incluyendo los archivos que corresponden a la parte del Slider (https://alkemy-labs.atlassian.net/browse/OGN2-53) y que deben estar para revisión en otro PR. Remueve esos archivos y si ya está esa funcionalidad del Slider, hacerlo en su rama correspondiente y crear PR para esa revisión. Acá solo debe existir cambios para el alcance del OGN2-51

2022-11-03 20:49 UTC, JuanmeGarcia commented
Okay, no sabia eso, ahi lo modifico nuevamente. La pull request del slider ya esta creada!

2022-11-03 20:50 UTC, closed without merging

2022-11-08 01:40 UTC, milandre commented on src/App.js
> +import { BackOfficeDashboard, Home, OrganizationInfo, Register } from './Pages';
Problemas de importación acá. Hay dos carpetas: pages y Pages. Tienen que decidir en equipo con cual se quedan

2022-11-08 01:40 UTC, milandre commented on src/pages/index.js
> +export * from './Register'
El componente de Register no esta aca en pages, está en Pages

2022-11-08 01:40 UTC, milandre commented on src/pages/index.js
> +export * from './Home'
El componente de Home no esta aca en pages, está en Pages