Se termino el formulario de logeo (CSS Ligado al formulario "Register")
alkemyTech/React-SXXI-T2 pull request #19
Opened 2022-11-04 14:00 UTC by Keviin7A

2022-11-04 21:24 UTC, YamilChaju approved these changes

2022-11-08 02:40 UTC, milandre requested changes
@Keviin7A hay problemas con las importaciones en App.js. Por favor, revisar bien el archivo y arreglar los errores de consola y warnings para poder realizar la corrección del PR. Estos errores son algunos comentados en otros PR del equipo asi que sugiero se pongan de acuerdo para resolverlos

2022-11-08 02:40 UTC, milandre commented on src/Components/FormStyles.css
> +
Eliminar espacios en blanco extra

2022-11-10 18:04 UTC, milandre requested changes

2022-11-10 18:04 UTC, milandre commented on src/Components/Auth/LoginForm.jsx
> +    <form className="form-container" onSubmit={handleSubmit}>
Estaría bueno que el login comparta estilos similares con el de registro. Sugiero que te reunas con @CatrielNanthaveth para que lleguen a un acuerdo en este aspecto.

2022-11-11 15:49 UTC, Keviin7A commented on src/Components/Auth/LoginForm.jsx
> +  const RegexPassword =/^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$ %^&*-]).{6,}$/;
Se espera confirmación de aceptación de nueva validación en https://alkemy-labs.atlassian.net/browse/OGN2-26

2022-11-11 15:50 UTC, Keviin7A commented on src/Components/FormStyles.css
> +
Se eliminaron los espacios en blanco.

2022-11-11 15:50 UTC, Keviin7A commented on src/Components/Auth/LoginForm.jsx
> +  const navega = useNavigate();
Se corrigió el nombre de la variable a inglés.

2022-11-11 16:03 UTC, Keviin7A commented on src/Components/Auth/LoginForm.jsx
> +    <form className="form-container" onSubmit={handleSubmit}>
Se corrigió que los bordes de los input se coloreen en rojo cuando hay un error.
Por favor, podría indicarme si hay otro lugar especifico debería hacer la correción de los estilos?

Login
![image](https://user-images.githubusercontent.com/54379455/201381208-28d340ff-f934-4cba-bec1-143173320d16.png)

Register
![image](https://user-images.githubusercontent.com/54379455/201378897-af3d791b-0e8d-4bbc-936d-e0b4ef446c5d.png)


![image](https://user-images.githubusercontent.com/54379455/201381117-f0211b90-d43c-48e5-bfa5-289ea5685d9a.png)

2022-11-11 17:33 UTC, milandre requested changes

2022-11-11 17:33 UTC, milandre commented on src/Components/Auth/LoginForm.jsx
> +  const navega = useNavigate();
Todavía aparece en la rama en español. Revisa que hayas subido los ultimos cambios a esta rama: `feature-ogn2-26`

2022-11-11 17:33 UTC, milandre commented on src/Components/FormStyles.css
> +
Todavía aparece en la rama. Revisa que hayas subido los ultimos cambios a esta rama: `feature-ogn2-26`

2022-11-11 17:33 UTC, milandre commented on src/Pages/Login.jsx
> +import logo from "../resources/logo/LOGO-SOMOS_MAS.png";
Error de importación. Arreglar

2022-11-11 17:33 UTC, milandre commented on src/Pages/Login.jsx
> +import img2 from "../resources/logo/img2.png";
Error de importación. Arreglar

2022-11-11 17:33 UTC, milandre commented on src/Components/Auth/LoginForm.jsx
> +    <form className="form-container" onSubmit={handleSubmit}>
Hay errores en la rama todavía con respecto a las importaciones y falta actualizar la rama con los cambios de development. Mientras hacia esto para probar de nuevo (no debería estar haciendo esto cada vez que quiera probar. Esta rama debe estar sin errores de ejecución), pude revisar y vi que tienen la misma base, asi que está bien. Igual, tienes que arreglar los errores que aparecen todavia en la rama antes de aprobar.

2022-11-11 17:49 UTC, milandre commented on src/Components/Auth/LoginForm.jsx
> +  const RegexPassword =/^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$ %^&*-]).{6,}$/;
Ahi dejé mi respuesta en https://alkemy-labs.atlassian.net/browse/OGN2-26

2022-11-11 18:51 UTC, Keviin7A commented
Por favor, podrías indicarme si lo hice correctamente el nuevo commit ?

2022-11-14 13:08 UTC, closed without merging

2022-11-14 13:21 UTC, Keviin7A commented
Cierro el commit ya que se realizó un git pull de development nuevamente y tengo que modificar actualizaciones de css que realizaron sin considerar el login form. En breves hago nuevamente el push.