Finalización del componente de listado de miembros
alkemyTech/React-SXXI-T2 pull request #20
Opened 2022-11-04 20:15 UTC by CatrielNanthaveth

Se ha creado el componente ListMembers. Se agregó como ruta de manera temporal para su visualización

2022-11-04 21:26 UTC, YamilChaju approved these changes

2022-11-08 03:05 UTC, milandre commented on src/Components/Members/ListMembers.jsx
> +                            <Card size="default" title={member.name} className="individual-card">
Acá se espera que se use el componente reutilizable de Card que se especifica en esta historia: https://alkemy-labs.atlassian.net/browse/OGN2-60

Mientras tanto, puedes ir acomodando los estilos para que sea una lista que tenga varias columnas por fila para representar a los miembros. Se debe ver algo parecido a esto que se encuentra en la sección de Staff del figma:
![image](https://user-images.githubusercontent.com/5572252/200465299-3a355552-c671-443f-a607-36b35dc5c370.png)

2022-11-08 03:19 UTC, milandre requested changes

2022-11-08 03:19 UTC, milandre commented on src/Components/Members/ListMembers.jsx
> +            const { data } = await axios.get("https://ongapi.alkemy.org/api/members");
Acá el endpoint no sigue los estilos o decisiones definidas en su Design System: Todas las constantes que no varíen serán escritas en upper snake case

Referencia: https://detailed-sloth-8b7.notion.site/Design-System-a9c4ee1c810b46f784840c350529d050

2022-11-09 20:15 UTC, CatrielNanthaveth commented on src/Components/Members/ListMembers.jsx
> +                            <Card size="default" title={member.name} className="individual-card">
No entiendo la forma en que se presentan las cards. ¿Solo mostrarían el nombre y el puesto, junto a la imagen como background? ¿Qué hago con los links? En el figma hay un listado de cards y un detalle en grande de un miembro con una descripción larga, pero el endpoint solo devuelve una descripción corta (que en realidad es solo la ocupación, no una descripción en sí), ¿qué hago? 
 Por otra parte, las cards tienen que ser elementos clickeables que traigan la card que clickeamos en primer plano y nos dé el detalle?

2022-11-13 16:47 UTC, milandre commented on src/Components/Members/ListMembers.jsx
> +                            <Card size="default" title={member.name} className="individual-card">
El estilo es libre, es decir, pueden guiarse por lo que aparece en Jira o hacer uno ustedes. Lo importante es que mantenga consistencia en las diferentes partes de la aplicación. La información presentada deberia ser name, image, description, facebookUrl, linkedinUrl. La parte del detalle no corresponde a esta historia de usuario.

2022-11-14 20:54 UTC, CatrielNanthaveth commented
@milandre se han cambiado las cosas, no estoy seguro de haber entendido bien al respecto de visualización del listado. 
Por otra parte, se agregó la ruta /list-members temporalmente para su visualización, cuando se realice la task de renderización del list-members se eliminará y será reemplazada por la page

2022-11-16 11:51 UTC, milandre requested changes

2022-11-16 11:51 UTC, milandre commented on src/Sass/components/_members.scss
> +@media screen and (max-width: 1023px){
falta añadir al `main.scss` esta importación para que se apliquen los estilos:
`@import './components/members';`

2022-11-16 11:51 UTC, milandre commented on src/Components/Members/ListMembers.jsx
> +                        <ul>
falta colocarle una key prop acá o en la Card

2022-11-16 16:05 UTC, milandre approved these changes
@CatrielNanthaveth faltaria despues modificar con el que va a ser el componente <Card /> genérico

2022-11-16 16:20 UTC, CatrielNanthaveth commented
Dejo la PR abierta hasta poder agregar el componente entonces

2022-12-13 17:21 UTC, milandre commented
@CatrielNanthaveth revisar este PR a ver si ya es posible hacerle merge. Está aprobado hace bastante

2022-12-13 21:51 UTC, merged