finalización del feature
alkemyTech/React-SXXI-T2 pull request #22
Opened 2022-11-06 19:34 UTC by CatrielNanthaveth

Se realizó la obtención de las novedades desde la API y se creó la renderización del listado en una view. Falta cambiar el title por el componente, sin embargo éste no está disponible.

2022-11-06 22:48 UTC, YamilChaju approved these changes

2022-11-09 11:53 UTC, milandre requested changes

2022-11-09 11:53 UTC, milandre commented on src/Components/News/news.css
> +
Si no hay estilos que aplicar acá en esta media quety, se debería quitar

2022-11-09 11:53 UTC, milandre commented on src/pages/News/News.jsx
> +            const { data } = await axios.get("https://ongapi.alkemy.org/api/news");
Acá el endpoint no sigue los estilos o decisiones definidas en su Design System: Todas las constantes que no varíen serán escritas en upper snake case

Referencia: https://detailed-sloth-8b7.notion.site/Design-System-a9c4ee1c810b46f784840c350529d050

2022-11-09 11:53 UTC, milandre commented on src/pages/News/News.jsx
> +            data.data.map((value) => {
La función map te genera un nuevo arreglo donde la llamada a la función te retorna el o los valores nuevos para ese arreglo a partir de cada uno de los elementos en data.data. Este map no está retornando nada y es necesario. Volver a plantear la lógica de esta parte.

Más información acerca de map: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Array/map

2022-11-09 11:53 UTC, milandre commented on src/Components/News/NewsList.js
> +                                        <img src={element.image} className="card-image" />
Falta el alt prop en img

2022-11-09 11:53 UTC, milandre commented on src/Components/News/NewsList.js
> +                            <li key={element.id} className='cards' >
El listado de las cards aparece centrado y lo ideal es que se vea como la referencia a la sección de Novedades del Figma

2022-11-14 18:53 UTC, CatrielNanthaveth commented on src/Components/News/NewsList.js
> +                            <li key={element.id} className='cards' >
con eso se refiere a que las cards tienen que visualizarse en un slider?
![image](https://user-images.githubusercontent.com/91494648/201741919-cdd9698b-672a-4da1-929e-28b3355100f7.png)
algo así?
el botón de Inicio también debería incluirlo? en el ticket no menciona nada del botón. 
por otro lado, las imagenes las debería recortar o mantener su tamaño?

2022-11-16 16:16 UTC, milandre requested changes
@CatrielNanthaveth las cosas de News estan en la carpeta de pages y no Pages. Salen estos errores:
![image](https://user-images.githubusercontent.com/5572252/202234163-f0ae201c-f266-41d0-b94d-359cb2559726.png)

Mover las cosas de News a Pages y modificar importaciones. Verificar que se ejecute sin errores y que todo esté ok con la rama para poder terminar de revisar y aprobar

2022-11-29 15:55 UTC, milandre approved these changes

2022-11-29 19:04 UTC, merged