Feature/ogn2 32
alkemyTech/React-SXXI-T2 pull request #24
Opened 2022-11-08 02:42 UTC by YamilChaju

Formulario de edicion de Home finalizado, solo falta descomentar las slides una vez que este terminado el SlidesForm.
Se realizo obteniendo el texto de bienvenida de la api y plasmandolo al input, asi se puede editar el texto original, o en todo caso borrarlo y escribir uno nuevo. Al hacer submit se realiza un put y si se realizo correctamente sale una notificacion corroborando el texto nuevo, en caso de haber algun problema, se muestra un mensaje de error.

2022-11-10 19:50 UTC, milandre requested changes

2022-11-10 19:50 UTC, milandre commented on src/Components/Home/HomeForm.jsx
> +            let endPoint = `https://ongapi.alkemy.org/api/${text}`;
acá deberia ser el llamado a la API de Slides https://ongapi.alkemy.org/api/docs#/Slide

2022-11-10 19:50 UTC, milandre commented on src/Components/Home/HomeForm.jsx
> +        getDataSlides("members");
esto no iria porque son las Slides de la organización proveniente del endpoint de Slides

2022-11-10 19:50 UTC, milandre commented on src/Components/Home/HomeForm.jsx
> +        getDataSlides("testimonials");
esto no iria porque son las Slides de la organización proveniente del endpoint de Slides

2022-11-10 19:50 UTC, milandre commented on src/Components/Home/HomeForm.jsx
> +        getDataSlides("news");
esto no iria porque son las Slides de la organización proveniente del endpoint de Slides

2022-11-10 19:50 UTC, milandre commented on src/Components/Home/HomeForm.jsx
> +            {/* <SlidesForm data={homeValues.slideStaff} />
Acá faltaría mostrar la parte de edición de 3 de esos Slides y hacer la lógica del llamado a la API para modificar esos datos.

2022-11-10 19:50 UTC, milandre commented on src/Components/Home/HomeForm.jsx
> +        setOrganizationData(currValues => ({ ...currValues, welcome_text: values.welcome }))
Acá en el onSubmit falta incluir la actualización de la información de los 3 Slides

2022-11-15 01:37 UTC, YamilChaju commented on src/Components/Home/HomeForm.jsx
> +            {/* <SlidesForm data={homeValues.slideStaff} />
Tengo entendido que SlidesForm ya es un formulario, no lo puedo insertar dentro de otro form, ademas leyendo la card de los SlidesForm que esta realizando Nico, dice que ya ahi mismo se hacen los llamados a la api, validaciones y todo lo demas, por eso pienso que lo unico que tengo que pasarle por props es el id del slide a modificar.

![Capture](https://user-images.githubusercontent.com/50427031/201805142-c4a02ab5-01c2-4b60-b6f9-5a6ebc2e56ac.JPG)

2022-11-18 04:44 UTC, closed without merging