Features/ogn2 31
alkemyTech/React-SXXI-T2 pull request #33
Opened 2022-11-10 22:28 UTC by garcianico

2022-11-12 18:14 UTC, garcianico commented
Realicé los cambios que solucionan los conflictos.

2022-11-16 18:03 UTC, milandre commented on src/Components/Slides/SlidesForm.jsx
> +                id='input-order'
El id es `order`

2022-11-16 18:06 UTC, milandre commented on src/Components/Slides/SlidesForm.jsx
> +                        <div>
Colocar la imagen de preview con un tamaño por defecto para que no se muestren imagenes con diferentes tamaños

2022-11-16 18:07 UTC, milandre commented on src/Components/Testimonials/TestimonialsForm.jsx
> +                                <div className='testimonial-image-Preview' style={{ content: `url(${imagePreview})` }}></div>
colocar la imagen de preview con un tamaño por defecto para que no se muestren imagenes con diferentes tamaños

2022-11-16 18:07 UTC, milandre commented on src/Components/Slides/SlidesForm.jsx
> +            onSubmitService(
¿Qué pasa si en la vista de modificación no quiero modificar la imagen? Me sale un error y no puedo enviar. Se deberia poder actualizar cualquiera de los otros valores sin necesidad de cambiar la imagen.

Adjunto imagen del error:
![image](https://user-images.githubusercontent.com/5572252/202258989-8c3d03ad-6f0a-4520-9702-21eab3701b88.png)

2022-11-16 18:22 UTC, milandre requested changes

2022-11-16 18:22 UTC, milandre commented on src/Components/Testimonials/TestimonialsForm.jsx
> +            <form className="testimonial-form-container" onSubmit={handleSubmit}>
Revisar estilos para hacer el formulario responsive

2022-11-16 18:22 UTC, milandre commented on src/Components/Slides/SlidesForm.jsx
> +        <form className="form-container" onSubmit={handleSubmit} >
Revisar estilos para hacer el formulario responsive

2022-11-17 16:26 UTC, milandre requested changes
No me deja modificar en la vista de Modificar Testimonio sin antes cambiar la imagen. Esto no deberia pasar ya que me deberia dejar modificar los otros campos sin necesidad de cambiar la imagen. 

Adjunto el error que me pasa cuando intento modificar el testimonio con id 535: 
![image](https://user-images.githubusercontent.com/5572252/202501252-7be64dba-6675-4548-8741-cd2bc4d0a9be.png)

Revisar la parte de las validaciones y el `onSubmitService` no debe estar ligado al `fileReader` ya que en el caso de modificacion de cualquiera de los otros campos, el submit no se ejecuta. Solo se ejecuta si se carga otra imagen.

2022-11-23 18:16 UTC, milandre requested changes

2022-11-30 23:30 UTC, merged