Feature/ogn2 60
alkemyTech/React-SXXI-T2 pull request #36
Opened 2022-11-13 18:37 UTC by JuanmeGarcia

2022-11-13 18:39 UTC, JuanmeGarcia commented
Cree el componente de card, ahora voy a realizar aparte el componente carrusel para que se puedan renderizar como se espera. Voy a crear una branch para el carrusel a partir de la rama que pushee

2022-11-17 17:02 UTC, milandre requested changes

2022-11-17 17:02 UTC, milandre commented on src/Pages/Home.jsx
> +// import { Slider } from '../Components/Slider'
Borrar comentario

2022-11-17 17:02 UTC, milandre commented on src/Pages/Home.jsx
> +            {/* <Slider /> */}
Borrar comentario

2022-11-18 12:38 UTC, JuanmeGarcia commented on src/Components/Card/Card.jsx
> +    const { data } = useCard(type)
Claro, luego se renderiza en un contenedor carrousel, el tema es que no tengo otra forma de testearlo si no me traigo la data de algun lado para ver como quedaria

2022-11-18 12:39 UTC, JuanmeGarcia commented on src/Components/Card/Card.jsx
> +    const cardType = type === types.news ? 'news' : type === types.staff ? 'staff' : 'testimonial'
Y como podria hacer para bajar este acoplamiento en consecuencia?

2022-12-05 14:31 UTC, milandre commented on src/Components/Card/Card.jsx
> +    const cardType = type === types.news ? 'news' : type === types.staff ? 'staff' : 'testimonial'
@Romycavallaro esto falta cambiar

2022-12-05 14:31 UTC, milandre commented on src/Components/Card/Card.jsx
> +    const { data } = useCard(type)
@Romycavallaro esto falta cambiar

2022-12-05 14:31 UTC, milandre commented on src/Components/Card/Card.jsx
> +        <article className={`card-container card-container--${cardType}`}>
@Romycavallaro esto falta

2022-12-05 14:31 UTC, milandre commented on src/Components/Card/Card.jsx
> +
@Romycavallaro revisar esto

2022-12-19 15:55 UTC, milandre commented
Cierro PR porque algunos de los cambios comentados acá no se terminaron aplicando y los otros se encuentra en distintos PRs que ya han sido revisados

2022-12-19 15:55 UTC, closed without merging