Feature/ogn2 33
alkemyTech/React-SXXI-T2 pull request #38
Opened 2022-11-15 01:21 UTC by YamilChaju

Formulario reutilizable de creacion/modificacion de usuarios terminado, con todas las validaciones y visualizacion del profile_image

2022-11-21 20:40 UTC, milandre requested changes

2022-11-21 20:40 UTC, milandre commented on src/Components/Users/UsersForm.jsx
> +                values.password = data.password;
Falta colocar `values.profile_image` cuando el usuario lo tiene

2022-11-21 20:40 UTC, milandre commented on src/Components/Users/UsersForm.jsx
> +        setUsersValues(currValues => ({ ...currValues, ...values, profile_image: "" }))
Quitar el `profile_image: ""` de acá

2022-11-21 23:17 UTC, YamilChaju commented
@milandre se resolvieron los cambios requeridos, espero la confirmacion para hacer el merge. Gracias

2022-11-21 23:53 UTC, YamilChaju commented
@milandre se corrigio un bug por el cambio anterior y se agrego al post la misma condicion anteriormente aplicada en el put de users. Espero confirmacion para realizar el merge.

2022-11-23 18:15 UTC, milandre approved these changes

2022-11-24 04:58 UTC, merged