Feature/activities 50 57 58
alkemyTech/React-SXXI-T2 pull request #39
Opened 2022-11-15 13:46 UTC by Romycavallaro

@milandre listo para code review componente actividad

2022-11-23 19:31 UTC, milandre requested changes

2022-11-23 19:31 UTC, milandre commented on src/Components/Activities/ActivitiesList.js
> +    </div>
Con respecto a este componente, te dejo una sugerencia para que hagas y pruebes para que veas como queda. Los estilos te los dejo comentados en el .scss:
```
<>
      <h1 className="cardH1">Actividades</h1>
      <div className="list-container">
        {actividades.length > 0 ? (
          actividades.map((activity) => {
            return (
              <div className="cardAct" key={activity.id}>
                <img
                  className="imgCard"
                  src={activity.image}
                  alt=""
                />
                <div className="card-info">
                  <h3 className="titleH3">{activity.name}</h3>
                  <p className="description">{activity?.description?.substring(0, 150)}...</p>
                  <Link to={`/activities/${activity.id}`}>
                    <button className="verMas">Ver detalle</button>
                  </Link>
                </div>
              </div>
            );
          })
        ) : (
          <p>No hay actividades</p>
        )}
      </div>
    </>
 ```

2022-11-23 19:31 UTC, milandre commented on src/Components/Activities/Activities.scss
> +.list-container {
Sugerencia para que pruebes con lo que te comente en el archivo de ActivitiesList.js:
```
.list-container {
 display: grid;
 grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
 gap: 2rem;
 max-width: 100%;
 margin: 30px auto;
}
```

2022-11-23 19:31 UTC, milandre commented on src/Components/Activities/Activities.scss
> +.cardAct {
Sugerencia para que pruebes con lo que te comente en el archivo de ActivitiesList.js:
```
.cardAct {
    display: flex;
    background-color: #adb6d8;
    border-radius: 8px;
}
```

2022-11-29 20:13 UTC, merged

2022-12-06 12:04 UTC, Romycavallaro commented
@milandre no estoy ignorando los comentarios ni sugerencias
Simplemente que si yo aplico esto en css veo el codigo de esta manera

![image](https://user-images.githubusercontent.com/85654421/205906788-63bc7627-79d7-4a3a-9224-8bdfb18e2e32.png)

2022-12-06 20:18 UTC, milandre commented
> @milandre no estoy ignorando los comentarios ni sugerencias Simplemente que si yo aplico esto en css veo el codigo de esta manera
> 
> ![image](https://user-images.githubusercontent.com/85654421/205906788-63bc7627-79d7-4a3a-9224-8bdfb18e2e32.png)

No solo tendrias que modificar el scss. Tambien tienes que hacer cambios en el ActivitiesList.js. Tienes que quitar el 
<div className="card"> y que quede asi para que se note los cambios:
```
<>
      <h1 className="cardH1">Actividades</h1>
      <div className="list-container">
        {actividades.length > 0 ? (
          actividades.map((activity) => {
            return (
              <div className="cardAct" key={activity.id}>
                <img
                  className="imgCard"
                  src={activity.image}
                  alt=""
                />
                <div className="card-info">
                  <h3 className="titleH3">{activity.name}</h3>
                  <p className="description">{activity?.description?.substring(0, 150)}...</p>
                  <Link to={`/activities/${activity.id}`}>
                    <button className="verMas">Ver detalle</button>
                  </Link>
                </div>
              </div>
            );
          })
        ) : (
          <p>No hay actividades</p>
        )}
      </div>
    </>
```
También tendrías que revisar el orden de importación de los estilos de scss por si hay algunos que estén sobrescribiendo los que estás colocando para los de la lista de actividades. Se te debería ver algo asi:
![responsive_activities_list_example](https://user-images.githubusercontent.com/5572252/206013842-4cfe26b0-aa7f-4057-a824-b077a0a78cde.gif)