Feature/ogn2 51
alkemyTech/React-SXXI-T2 pull request #4
Opened 2022-10-30 20:25 UTC by JuanmeGarcia

drawer creado

2022-11-01 11:42 UTC, milandre commented on src/Components/BackOffice/SectionCard.jsx
> +            {/* //todo: modificar la etiqueta <h2></h2> por un component <Title /> */}
Como sugerencia:
En los PR finales no dejar comentarios o console.logs

2022-11-01 23:39 UTC, JuanmeGarcia commented on src/Components/BackOffice/SectionCard.jsx
> +            {/* //todo: modificar la etiqueta <h2></h2> por un component <Title /> */}
Tampoco comentarios para marcar cosas que uno tiene que hacer a futuro? deje el comentario para cuando se cree el componente <Title /> asi lo reemplazaba luego

2022-11-02 11:37 UTC, milandre commented on src/Components/BackOffice/SectionCard.jsx
> +            {/* //todo: modificar la etiqueta <h2></h2> por un component <Title /> */}
Puedes dejar ese comentario en el Jira

2022-11-02 18:33 UTC, milandre requested changes
@JuanmeGarcia cambia la rama de main a development. Recuerda actualizar tu rama feature/OGN2-51 con los últimos cambios hechos a development y a partir de ahi trabajar los cambios.

2022-11-02 18:33 UTC, milandre commented on src/App.js
> +import 'antd/dist/antd.css';
Cambiar import a la forma con el .min.css
`import 'antd/dist/antd.min.css';`

Sugerencia:
Mover los import de los estilos .css, .scss al index.js luego de las importaciones de los componentes/librerías y antes del library.add(faNewspaper)

2022-11-02 18:33 UTC, milandre commented on src/pages/BackOfficeDashboard.jsx
> +                    <Link to={`/backoffice/usuarios`}>
Recordar modificar los to de los links para redirigir a las rutas correctas

2022-11-03 00:02 UTC, JuanmeGarcia commented on src/App.js
> +import 'antd/dist/antd.css';
Queria ponerlo en la rama development pero me sale una alerta y no me lo permite. De todos modos ya esta mergeado a la rama development los cambios. Voy a crear ahora una rama bugfix/ogn2-51 haciendo los cambios pertinentes.

2022-11-03 00:03 UTC, JuanmeGarcia commented on src/pages/BackOfficeDashboard.jsx
> +                    <Link to={`/backoffice/usuarios`}>
Lo deje asi de forma momentanea ya que no tenemos todavia las rutas creadas para la redireccion

2022-11-03 00:04 UTC, JuanmeGarcia commented on src/Components/BackOffice/SectionCard.jsx
> +                { image() }
Los deje cuadrados ya que pensaba que no se debia seguir el disenio en su 100%. Sino les creo un marco y le coloco un border-radius: 100% para hacerlos rounded.

2022-11-03 20:49 UTC, milandre commented on src/Components/BackOffice/SectionCard.jsx
> +                { image() }
Como dice el comentario: Si lo van a dejar cuadrado, añadan un poco de margen entre el título, el ícono y el botón de ir para que no se vea el icono de fontawesome tan junto al título.

2022-11-03 20:54 UTC, JuanmeGarcia commented on src/Components/BackOffice/SectionCard.jsx
> +                { image() }
Agregue un poco mas de margen. Estaba em 4 px, lo subi a 12px

2022-11-07 21:49 UTC, closed without merging