Feature/37
alkemyTech/React-SXXI-T2 pull request #42
Opened 2022-11-17 18:33 UTC by Romycavallaro

@milandre subo formulario de edición y creación de proyectos para corregir

2022-11-24 18:47 UTC, milandre requested changes
El formulario de ProjecstForm necesita varias modificaciones que ya fueron realizadas en el de TestimonialsForm del PR #33 y están en la rama `features/OGN2-31`. Sugiero que te pongas en contacto con @garcianico para que te ayude a hacer los cambios pertinentes en cuanto a las validaciones, estilos y funcionamiento en general. No olvides probar todo y que este todo funcional antes de hacer push y pedir revision de los cambios

2022-11-24 18:47 UTC, milandre commented on src/Components/Auth/RegisterForm.jsx
> +import { basicSchema } from './RegisterSchema';
Error de importación acá. En los otros PR que he corregido, también está este inconveniente. Se debería cambiar a `./registerSchema` o cambiar el nombre del archivo

2022-11-24 18:47 UTC, milandre commented on src/App.js
> +          <Route path="/backoffice/create-project" element={<ProjectsForm/>} />
Falta agregar la ruta para editar el Proyecto

2022-11-24 18:47 UTC, milandre commented on src/Components/Projects/ProjectsForm.js
> +    due_date: yup.date().required('Completar el campo fecha'),
El campo de due_date no es requerido

2022-11-26 14:15 UTC, Romycavallaro commented
@milandre Ok modificado las correcciones y comentarios realizados
Ok para code review

2022-11-29 23:12 UTC, milandre commented
@Romycavallaro sigue estando desactualizado El formulario con respecto a las correcciones que le hice a @garcianico en El formulario de TestimonialsForm. Sugiero que SE junten o en su defecto, revises los ultimos cambios que subió en su rama del PR #33

2022-12-03 15:26 UTC, Romycavallaro commented
@milandre favor controlar cambios realizados
Gracias

2022-12-05 13:00 UTC, milandre requested changes

2022-12-05 13:00 UTC, milandre commented on src/Components/Projects/ProjectsForm.js
> +    image: yup.string().matches(jpgRegExp, {message: 'La imagen debe ser un archivo .jpg o .png', excludeEmptyString: true}),
Falta esto acá:
```
image: 
            (id)
                ? Yup
                    .string()
                    .matches(jpgRegExp, {message: 'La imagen debe ser un archivo .jpg o .png', excludeEmptyString: true})
                : Yup
                    .string()
                    .matches(jpgRegExp, {message: 'La imagen debe ser un archivo .jpg o .png', excludeEmptyString: true})
                    .required('La imagen es un dato requerido.')
```

2022-12-05 13:06 UTC, milandre approved these changes

2022-12-05 13:10 UTC, merged