Realización inicial del feature
alkemyTech/React-SXXI-T2 pull request #43
Opened 2022-11-17 22:10 UTC by CatrielNanthaveth

Se creó el scss del footer
se modificó el componente Footer ya creado previamente

2022-11-17 22:13 UTC, CatrielNanthaveth commented
Hay varios links que no funcionan justamente porque aún no están esas Pages. Cuando estén listas y mergeadas en development, voy a reemplazar los <Link to="/">

2022-11-24 11:53 UTC, milandre requested changes

2022-11-24 11:53 UTC, milandre commented on src/App.js
> +          <Route path='/footer' element={<Footer />} />
Eliminar esta linea. Puedes colocar este componente en el de <Home /> por ahora. Lo ideal seria que tanto Footer como Header esten en un componente de Layout que luego puedan colocar como padre de las rutas y asi no repetir codigo cuando integren Header y Footer a su app

2022-11-24 11:53 UTC, milandre commented on src/Sass/components/_footer.scss
> +        display: flex;
Agregar estos estilos a cada `footer-container` para que sea fixed abajo de cada pantalla:
```
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
```

2022-11-24 11:53 UTC, milandre commented on src/Sass/components/_footer.scss
> +        display: grid;
Agregar estos estilos a cada `footer-container` para que sea fixed abajo de cada pantalla:
```
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
```

2022-11-24 16:26 UTC, milandre approved these changes
@CatrielNanthaveth falta que borres la importacion del Footer que ya no se esta usando en App.js. Haces eso y ya estaria listo para hacerle merge

2022-11-24 16:26 UTC, milandre commented on src/App.js
> -          <Route path='/footer' element={<Footer />} />
Te falto borrar la importacion del Footer en este archivo

2022-11-25 00:00 UTC, merged