Feature/62
alkemyTech/React-SXXI-T2 pull request #49
Opened 2022-11-22 14:26 UTC by Romycavallaro

@milandre Screen Listado de Actividades (backoffice)

2022-12-01 04:33 UTC, milandre requested changes
@Romycavallaro tienes cambios a realizar. Revisar con @CatrielNanthaveth el estilo del tamaño de las imágenes para mantenerlos igual

2022-12-01 04:33 UTC, milandre commented on src/Components/Auth/RegisterForm.jsx
> +import { basicSchema } from './RegisterSchema';
Otra vez error acá de importación

2022-12-01 04:33 UTC, milandre commented on src/Components/Activities/ActivitiesListBackoffice.js
> +          console.log(axios.delete(endPoint + "activities/" + record.id));
endPoint ya tiene activities incluido. Aca salta error.
Dejar la llamada de axios.delete afuera del console.log

2022-12-01 04:33 UTC, milandre commented on src/Components/Activities/ActivitiesListBackoffice.js
> +          return pre.filter( record.id)
Error en el filter. Leer como se usa aca: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

2022-12-04 19:04 UTC, Romycavallaro commented
@milandre Ok modificado segun comentarios
Favor revisar. gracias

2022-12-05 14:36 UTC, milandre requested changes

2022-12-05 14:36 UTC, milandre commented on src/Components/Activities/ActivitiesListBackoffice.js
> -          console.log(axios.delete(endPoint + "activities/" + record.id));
Esto no puede quedar vacio porque si no, no funciona el deleteData que esta mas abajo. Aca debe ir la llamada al endpoint:
`axios.delete(endPoint + record.id)`

2022-12-06 11:57 UTC, Romycavallaro commented on src/Components/Activities/ActivitiesListBackoffice.js
> -          console.log(axios.delete(endPoint + "activities/" + record.id));
Ok @milandre corregido
Aguardo

2022-12-06 12:27 UTC, Romycavallaro commented on src/Components/Activities/ActivitiesListBackoffice.js
> -          console.log(axios.delete(endPoint + "activities/" + record.id));
Se modifico responsive y arreglo de imagenes

2022-12-11 13:31 UTC, Romycavallaro commented
@milandre se agrego barra de busquedas al listado

2022-12-14 21:52 UTC, milandre requested changes
@Romycavallaro de acá solo falta arreglar unas cosas. Simplemente ve a la rama de `feature/62` y modifica lo que esta ahi y le haces push. Si ves que se complica por favor, hazlo saber para ayudarte. Estaría también bueno que te tomes un tiempo y repases los comandos de git

2022-12-14 21:52 UTC, milandre commented on src/Components/Activities/ActivitiesListBackoffice.js
> +          axios.delete(API + 'activities' + record.id);
Acá te falta agregar `/` al `activities`. Sería `activities/`

2022-12-14 21:52 UTC, milandre commented on src/Components/Auth/RegisterForm.jsx
> +import { basicSchema } from './RegisterSchema';
@Romycavallaro falta arreglar acá la importación que es `./registerSchema`

2022-12-15 11:26 UTC, Romycavallaro commented
Buen dia @milandre ya estan realizados los dos cambios que me dejaste en comentarios
AGuardo tu ok

2022-12-19 15:39 UTC, milandre approved these changes

2022-12-19 17:03 UTC, merged