Feature/ong2 72 creacion de metodo reutilizable patch
alkemyTech/React-SXXI-T2 pull request #53
Opened 2022-11-24 12:16 UTC by Romycavallaro

@milandre favor controlar code para merge. gracias

2022-11-29 16:00 UTC, milandre requested changes

2022-11-29 16:00 UTC, milandre commented on src/Services/privateApiService.js
> +export const Get = () => {
Borrar bloque comentado

2022-11-29 17:41 UTC, Romycavallaro commented on src/Services/privateApiService.js
> +export const Get = () => {
@milandre listo borrado y realizado el push

2022-12-06 23:00 UTC, milandre commented
@Romycavallaro no cierres PR sin antes indicar El por qué lo haces. ¿Qué pasó con este? No está aprobado todavia

2022-12-06 23:03 UTC, Romycavallaro commented
@milandre quise  hacer un comentario.

2022-12-14 21:55 UTC, milandre approved these changes

2022-12-15 12:26 UTC, merged