Feature/ONG2-72 extension de servicios de http a componente User
alkemyTech/React-SXXI-T2 pull request #67
Opened 2022-12-01 17:34 UTC by Romycavallaro

@milandre favor revisar para merge gracias

2022-12-05 21:42 UTC, milandre requested changes
@Romycavallaro falta modificar en UsersForm las llamadas a los endpoint por estas que se encuentran aca

2022-12-06 12:35 UTC, Romycavallaro commented
@milandre veo que ya estan integrados

![image](https://user-images.githubusercontent.com/85654421/205914155-52ad77c9-c1ea-4d6b-9585-fff4cbb203a7.png)

2022-12-06 20:40 UTC, milandre requested changes
@Romycavallaro el componente de UsersForm está en la ruta del backoffice. Como es del backoffice, tiene que usar los servicios de este archivo que estás agregando y no los que se encuentran importados desde el Services/publicApiService.

Esta linea del archivo UsersForm no debe estar:
![image](https://user-images.githubusercontent.com/5572252/206018234-9a4ce278-2ddc-4a55-b7db-e3fb122b833f.png)

Debe ser reemplazada por el getUsers, postUsers, putUser, deleteUser de este archivo UserService según corresponda en UsersForm

2022-12-06 20:40 UTC, milandre commented on src/Components/Users/UserService.js
> +export const postActivity = values => {
Acá debería ser postUsers

2022-12-19 16:08 UTC, milandre approved these changes

2022-12-19 20:35 UTC, merged