Feature/ong2 83 servicio http home
alkemyTech/React-SXXI-T2 pull request #69
Opened 2022-12-01 18:01 UTC by Romycavallaro

@milandre ok para revision
gracias

2022-12-05 21:57 UTC, milandre requested changes

2022-12-05 21:57 UTC, milandre commented on src/Pages/Home/HomeService.js
> +import { getData, putData, postData } from "Services/privateApiService";
Las peticiones del Home deben venir del publicApiService

2022-12-15 13:27 UTC, milandre commented on src/Pages/Home/HomeService.js
> +import { getData, putData, postData } from "Services/privateApiService";
@Romycavallaro falta modificar esto

2022-12-15 14:40 UTC, Romycavallaro commented
@milandre en el commit 347856f estaba la corrección de esto... no tengo comentarios tuyos sobre ese
Aguardo
Gracias

2022-12-19 16:10 UTC, milandre approved these changes

2022-12-19 18:02 UTC, merged